version: "3.8"

services:
  app:
    image: node:18-alpine
    container_name: todo_app_part2  # different container name
    command: sh -c "yarn install && yarn run dev"
    ports:
      - "3000:3000"  # same port is okay on different instance
    working_dir: /app
    volumes:
      - ./app_code:/app   # volume where Jenkins pipeline will mount your code
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mysql:
    image: mysql:8.0
    container_name: todo_mysql_part2
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data:
